changement méthode read_files
MetaboHUB-MetaToul-FluxoMet/IsoDesign pull request #11
Opened 2024-02-01 13:51 UTC by rkouakou06

J'ai essayé de rendre la méthode plus générale. Actuellement elle regarde si le path fourni est bien un string, si ce path existe et si le fichier est un fichier type CSV mais ça ne regarde plus les extensions. 
Je sais pas si c'est bon pour le coup

2024-02-01 15:14 UTC, rkouakou06 commented
J'ai rechangé la méthode read_file pour qu'elle soit moins générale du coup et plus spécifique aux fichiers obligatoires

2024-02-01 15:17 UTC, rkouakou06 commented
Y'a un return à la fin de la méthode que j'avais pas vu :'-o  
Du coup il ne sert à rien dans la méthode hein...

2024-02-05 15:57 UTC, rkouakou06 commented
Excuse moi ce n'est pas la bonne version que j'avais push :'-) 

J'ai fais la fonction check_files. J'ai l'impression qu'elle est un peu longue mais je n'ai réussi à faire que comme ça pour le moment (elle m'a un peu cassé la tête, j'y ai passé plus de temps que prévu...). Du coup la méthode vérifie le contenu des fichiers à partir du dictionnaire self.data_dict qui contient les fichiers importés (clé : nom des fichiers, valeur : contenu des fichiers sous forme de dataframe). J'extrais dans des set les colonnes à vérifier pour chacun des fichiers et je vérifie pour la plupart si leurs contenus est bien présent dans le réseau du fichier netw. Il y a également le check pour chaque fichier.

2024-02-06 08:51 UTC, llegregam requested changes

2024-02-06 08:51 UTC, llegregam commented on isodesign/process/calculation.py
> +                data = pd.read_csv(str(data_path), sep="\t", comment= "#", header=None if ext == ".netw" else 'infer')
Pas besoin de mettre le else ici, si la condition précédente est vérifiée tu vas avoir une erreur de générée du coup ça va arrêter l'éxécution du programme

2024-02-06 08:51 UTC, llegregam commented on isodesign/process/calculation.py
> +                data = pd.read_csv(str(data_path), sep="\t", comment= "#", header=None if ext == ".netw" else 'infer')
Trop bien l'utilisation du comment je ne savais même pas qu'il y avait ça dans la fonction read_csv ahah

2024-02-06 08:59 UTC, llegregam requested changes
Déjà direct je pense que tu peux créer des fonctions spécifique pour chaque type de fichier, ensuite tu les appelle directement dans le code de check files. Par exemple, pour gérer les .netw, tu peux créer une fonction _check_netw() qu'ensuite tu appelleras en dessous de : 
`if ".netw" in name_file:`

2024-02-06 10:43 UTC, rkouakou06 commented
J'ai séparé la méthode en plusieurs parties comme demandé. Du coup il y a une méthode pour chaque fichiers qui vérifie leurs contenu à partir du dictionnaire self.data_dict. Maintenant la méthode check_files récupère les colonnes à vérifier dans les fichiers et check si tous les métabolites contenu dans les différents fichiers sont bien présent dans le fichier netw.

2024-02-06 13:29 UTC, llegregam requested changes

2024-02-06 13:29 UTC, llegregam commented on isodesign/process/calculation.py
> +
Ici changer à self._check_netw

2024-02-06 13:29 UTC, llegregam commented on isodesign/process/calculation.py
> +    test_object1.read_files(r"U:\Projet\IsoDesign\isodesign\test-data\e_coli.miso")
Ils sont où mes chemins relatifs pour tester? :(

2024-02-06 13:29 UTC, llegregam commented on isodesign/process/calculation.py
> +                            netw_reactions.add(element)
Ici tu mets à la fois les noms de réactions et les noms de métabolites au même endroit, t'as pas peur par la suite que ça complique l'affaire? Genre si tu as besoin de manipuler seulement les noms des réactions tu fais comment?

2024-02-06 13:29 UTC, llegregam commented on isodesign/process/calculation.py
> +                # Set containing fluxes names only for free fluxes
For free fluxes? Pas net fluxes plutôt?

2024-02-06 13:29 UTC, llegregam commented on isodesign/process/calculation.py
> +            if ".tvar" in name_file:
Alors ici je ne comprends pas pq tu n'accèdes pas aux données du tvar directement avec:
`self.data_dict[".tvar"]`

2024-02-06 13:29 UTC, llegregam commented on isodesign/process/calculation.py
> +                    if x in ["Value"] and content[x].dtypes != np.float64 :
`if x == "Value"` serait plus compréhensible

2024-02-06 13:29 UTC, llegregam commented on isodesign/process/calculation.py
> +                        raise ValueError(f"Column 'Kind' in {name_file} must contains only NET, XCH or METAB type ")
Je me dis aussi y'a pas moyen de dire à l'utilisateur quelle valeur exactement renvoie l'erreur? Comme ça il peut le voir directement ça simplifie le debeugage

2024-02-06 13:29 UTC, llegregam commented on isodesign/process/calculation.py
> +            if ".miso" in name_file:
Même chose ici, tu peux directement faire `self.data_dict[".miso"]` pour accèder à ton dataframe de mesures isotopiques

2024-02-06 13:29 UTC, llegregam commented on isodesign/process/calculation.py
> +            if ".mflux" in name_file:
Même chose ici: `self.data_dict[".mflux"]`

2024-02-06 13:29 UTC, llegregam commented on isodesign/process/calculation.py
> +                for x in ["Flux", "Value", "SD"]:
Alors aussi une bonne pratique serait de rendre les colonnes des différents fichiers accessibles au niveau de la classe dans une variable de type constante

2024-02-06 14:41 UTC, llegregam commented on isodesign/process/calculation.py
> +            if ".tvar" in name_file:
Okok bon j'avoue c'est un peu bizarre ahah l'idée des dictionnaires c'est de justement pouvoir récupérer les données en utilisant les clefs. Si tu enlèves cette capacité là le dictionnaire n'est plus le meilleur contenaire pur les données. Je pense que tu peux modifier le code pour que tu puisses accèder aux fichier par leurs extension, et tu stock à chaque clé à la fois les données associées et le nom complet du fichier.

2024-02-06 14:47 UTC, rkouakou06 commented on isodesign/process/calculation.py
> +            if ".tvar" in name_file:
J'ai pas trop compris, en gros modifier le dictionnaire pour qu'il y ai comme clé l'extension du fichier et comme valeur le nom complet du fichier et les données associées ??

2024-02-06 15:03 UTC, llegregam commented on isodesign/process/calculation.py
> +            if ".tvar" in name_file:
Exactement

2024-02-07 13:57 UTC, rkouakou06 commented
Du coup j'ai effectué la plupart des changements que tu m'as demandé. Pour pouvoir comparer le contenu des fichiers, j'ai crée un dictionnaire "check_files_dict" qui permet de stocker les informations d'intérêt en fonction des fichiers.
Parmi les sous-fonctions, j'en ai crée une qui s'appelle "check_numerical_columns" et elle permet de vérifier le contenu des colonnes qui doivent contenir des valeurs numériques. Je l'ai crée pour éviter les répétitions dans les autres méthodes.

2024-02-08 09:25 UTC, llegregam requested changes

2024-02-08 09:25 UTC, llegregam commented on isodesign/process/calculation.py
> +                float(x)
Pas tout compris

2024-02-08 12:57 UTC, llegregam approved these changes

2024-02-09 08:49 UTC, llegregam approved these changes
C'est ok!! Tu peux maintenant passer à la simulation influx... :P

2024-02-09 08:49 UTC, llegregam commented on isodesign/process/calculation.py
> +                raise ValueError(f"'{reaction_name}' from a tvar file is not in the network file")
C'est bcp plus clair comme ça du coup :)

2024-02-09 08:49 UTC, merged