Dev
MetaboHUB-MetaToul-FluxoMet/IsoDesign pull request #12
Opened 2024-02-21 14:51 UTC by rkouakou06

Je suis désolée, je sais que y'a beaucoup de modifications d'un coup... 
Je vais plus faire ça promis !!! 

Dans le if __name__ == "__main__", j'ai commenté l'utilisation de la méthode d'influx, ça me mets une erreur que je comprends pas trop pour le moment.

2024-02-23 13:45 UTC, rkouakou06 commented
J'ai ajouté le module logging et mis des loggers dans le code. 
Pour le moment j'ai mis que des logger niveau error et info, je n'ai pas trop compris encore la différence entre debug et error... et je ne sais pas trop comment placer des niveaux comme warning ou critical.

2024-02-26 16:15 UTC, rkouakou06 commented
J'ai créé le dossier tests pour les tests unitaires. Pour le moment j'ai fais les tests pour les classes Isotopomer et LabelInput

2024-02-27 15:56 UTC, llegregam requested changes

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
>      def lower_bound(self):
Quelques petits docstrings ici pour expliquer les bounds seraient pas de refus!

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        Class containing the logic for handling labelling input generation for influx_si simulations.
Enlever le "for influx_si simulations"

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        self.isotopomers_group = isotopomers_group
On ne comprends pas là à quoi ça correspond ce isotopomers_group!

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        self.patterns = []
labellin_patterns serait plus explicite

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        for name_isotopomers, isotopomers in self.isotopomers_group.items():
isotopomer_name plutôt que name_isotopomers. 
Eviter de mettre au pluriel quand on nomme des objets seuls

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +            all_combinations = np.array(np.meshgrid(*fractions)).T.reshape(-1, len(fractions))
Là faudrait expliquer comment fonctionne cette ligne parce que c'est un peu cryptique ^^'

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +            first_isotopomer_fraction = np.subtract(np.ones([len(filtered_combinations)], dtype=Decimal), filtered_combinations.sum(axis=1))
Renommer plus clair et mettre un commentaire explicatif

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
>          self.mix = None
Besoin de plus d'explications là

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +            raise TypeError(msg)
Ici je pense c'est plutôt un ValueError qu'un type error

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        Method permit to copy the imported files in the linp folder.
Le début de cette phrase veut rien dire ^^
Je pense tu peux directement mettre "Copy the ..."

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        All the files that will be passed to influx_si simulations
le "simulations" est de trop ici

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +                raise ValueError(msg)
Là pour le coup c'est une erreur de type

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        self.mix = LabelInput(tracers)
Peut être faire des check ici des tracers?

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        logger.info("Isotopomers combinations : %s", self.mix.isotopomers_combination)
Use f-strings

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        of all combinations for one or multiple isotopomers groups.
A réecrire ce n'est pas clair là. N'hésite pas à utiliser chatGPT ou DeepL pour traduire du français à l'anglais!

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        features including the combinations for all isotopomer group.
Ici aussi je ne comprends pas trop cette phrase

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        informations.
On parle de _mapping_ dans ces cas là

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +            for pair in self.mix.isotopomers_combination["combinations"]:
Utilise le enumerate plutôt que le counter ici

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +                df.to_csv(os.path.join(str(output_path), f"{counter}.linp"), sep="\t")
Ici je ferais un log debug avec le dataframe, le numero d'itération et le chemin de sortie!

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        logger.info("Folder containing linp files has been generated on your current repertory.\n")
Ici je ferai un log de débug a la fin qui montrerait le dictionnaire dict_vmtf final

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        logger.info("Folder containing linp files has been generated on your current repertory.\n")
Tu peux mettre le chemin vers ce current directory (et non pas repertory ;) )

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        df = pd.DataFrame({key: pd.Series(value) for key, value in self.dict_vmtf.items()})
Il y a une méthode _from_dicts_ qui permets de faire des dataframes à partir d'un dictionnaire

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        logger.info("Vmtf file has been generated on the linp folder.")
in the linp folder, pas on

2024-02-27 15:56 UTC, llegregam commented on isodesign/process/calculation.py
> +        subprocess.run(["influx_s", "--prefix", prefix, "--mtf", f"{prefix}.vmtf", "--noopt"], shell=True, check=True)
Peut être explique le choix de mettre shell=True et check=True

2024-02-27 15:56 UTC, llegregam commented on isodesign/tests/test_isodesign.py
> +    assert isotopomer.num_carbon == 6
Faire des checks négatifs plutôt que positifs ici (vérifier qu'une erreur est renvoyée). Au pire fais un deuxième test identique mais qui vérifie que les erreurs sont bien gérés par les propriétés sous-jacentes

2024-02-27 15:56 UTC, llegregam commented on isodesign/tests/test_isodesign.py
> +            assert sum(pair) == 1
Attention! Avec les erreurs de floating points on pourrait avoir un test qui fail ici

2024-02-27 15:59 UTC, rkouakou06 commented on isodesign/tests/test_isodesign.py
> +            assert sum(pair) == 1
Je l'ai modifié dans mon code ce matin mais je l'ai pas encore commit ^^

2024-02-28 13:25 UTC, llegregam approved these changes

2024-02-28 13:25 UTC, llegregam commented on isodesign/process/calculation.py
> +        self.labellin_patterns = []
labellin**g**_patterns

2024-02-29 15:45 UTC, rkouakou06 commented
J'ai ajouté quelques tests unitaires dans le fichier test_isodesign.py, je sais pas s'ils sont bons.

2024-02-29 15:55 UTC, llegregam commented
Il manque le fixture pour "process" dans le conftest

2024-03-01 08:17 UTC, rkouakou06 commented
j'ai oublié de push le bon fichier conftest.py -_- ...

2024-03-13 09:38 UTC, llegregam approved these changes

2024-03-13 09:39 UTC, llegregam approved these changes

2024-03-13 09:39 UTC, merged