ajout methodes scoring dans outputParser class + docstrings
MetaboHUB-MetaToul-FluxoMet/IsoDesign pull request #13
Opened 2024-03-13 15:36 UTC by rkouakou06

2024-03-18 15:23 UTC, llegregam requested changes

2024-03-18 15:23 UTC, llegregam commented on isodesign/process/calculation.py
> +        self.path_isodesign_folder = Path(self.path_input_folder/"tmp_isodesign")
juste tmp

2024-03-18 15:23 UTC, llegregam commented on isodesign/process/calculation.py
> +        df = pd.DataFrame.from_dict({key: pd.Series(value) for key, value in self.vmtf_element_dict.items()})
Tu peux mettre:

`df = pd.DataFrame.from_dict(self.vmtf_element_dict)`

2024-03-18 15:23 UTC, llegregam commented on isodesign/process/calculation.py
>          subprocess.run(["influx_s", "--prefix", self.prefix, "--mtf", f"{self.prefix}.vmtf", "--noopt"], check=True)
Remplacer avec la fonction main

2024-03-18 15:23 UTC, llegregam commented on isodesign/process/calculation.py
> +                return imported_tvar["Value"]
On recommence :P
Ne pas oublier de changer structure dico pour avoir en clé les extensions

2024-03-18 15:23 UTC, llegregam commented on isodesign/process/calculation.py
> +    def output_parser(self, path_folder):
`generate_summary()`

2024-03-18 15:23 UTC, llegregam commented on isodesign/process/calculation.py
> +        logger.debug(f"dict_summarize_tvar: {self.dict_summarize_tvar}")
`dataframes = [pd.read_csv(files_path, sep="\t") for files_path in tvare_sim_paths]`
`summary = pd.concat(dataframes)`

2024-03-18 15:23 UTC, llegregam commented on isodesign/process/calculation.py
> +        scores.apply_score(self.summarize_tvar_df,"sum_sd", "flux_sd")
`def initialize_scoring:`
`self.scoring = ScoringHandler()`

2024-03-21 10:47 UTC, rkouakou06 commented
Par contre je ne sais pas si j'ai tout bien expliqué dans la méthode generate_summary()

2024-03-21 13:04 UTC, llegregam requested changes
C'est cool ça avance bien. Par contre à chaque nouveau push tu suis aussi tous les fichiers tests que tu as et qui changent à chaque fois. C'est pas nécessaire, je pense tu peux les enlever du suivi Git.

2024-03-21 13:04 UTC, llegregam commented on isodesign/process/calculation.py
> +        # list of dataframes containing interest information from tvar.sim files
Il faut expliquer ce qu'est l'information d'intérêt

2024-03-21 13:04 UTC, llegregam commented on isodesign/process/calculation.py
> +        tvar_sim_values = [pd.read_csv(files_path, sep="\t", usecols=["Value", "Name", "Kind"]) for files_path in tvar_sim_paths]
J'imagine que tu as une raison de faire ça mais je ne comprends pas tout. Tu pourras me l'expliquer demain?

2024-03-21 13:04 UTC, llegregam commented on isodesign/process/calculation.py
> +        self.summary_dataframe = pd.merge(merged_tvar.drop(["Id", "Comment", "Type", "Value_tvar"], axis=1), pd.concat(tvar_sim_dataframes, axis=1, join="inner"), on=[ "Name","Kind"])
Je vois que tu as pris en compétences sur les merge. Bravo! Par contre faudras m'expliquer le drop de toutes les colonnes là mdr

2024-03-21 13:04 UTC, llegregam commented on isodesign/process/calculation.py
> +        # merge the "merged_tvar" dataframe, keeping only columns of interest, with concatenated dataframes from the "tvar_sim_dataframes" list
Columns of interest il faut expliciter un peu plus

2024-03-21 13:07 UTC, llegregam requested changes

2024-03-21 13:07 UTC, llegregam commented on isodesign/process/calculation.py
> +            # Going to the folder containing all the file to use for influx_s
Dis plutôt "change directory to" au lieu de "Going to"

2024-03-21 13:07 UTC, llegregam commented on isodesign/process/calculation.py
>              logger.exception(f"An error occurred during influx_s execution: {str(e)}")
En fait je viens de capter pas besoin de stocker l'exception dans e et le renvoyer parce que logger.exception s'en occupe déjà

2024-03-21 13:33 UTC, rkouakou06 commented on isodesign/process/calculation.py
> +        tvar_sim_values = [pd.read_csv(files_path, sep="\t", usecols=["Value", "Name", "Kind"]) for files_path in tvar_sim_paths]
ah demain je suis pas là ^^ 
on peut faire une visio si t'es dispo

2024-03-25 13:25 UTC, llegregam approved these changes
Super boulot!

2024-03-25 13:25 UTC, merged