Develop
MetaboHUB-MetaToul-FluxoMet/IsoDesign pull request #2
Opened 2024-01-10 16:10 UTC by rkouakou06

___

2024-01-10 16:50 UTC, llegregam requested changes
Un bon début! Quelques changements à implémenter avant de passer à la suite ;)

2024-01-10 16:50 UTC, llegregam commented on isodesign/io.py
> +        self.mflux = []
Pourquoi initialiser les attributs sous forme de liste alors que plus tard tu y mets des dataframes? Si jamais moi dans ces cas là je mets juste None quand j'initialise mes attributs :)

2024-01-10 16:50 UTC, llegregam commented on isodesign/io.py
> +            print(f"The input file is not in right type.")
Ici tu as mis trois fonctions qui se ressemblent énormément. N'y a-t_il pas une façon que tu pourrais les rassembler en une seule focntion "read_file"?
Aussi j'ai vu qu'a certains endroits le code est en anglais et à d'autres c'est en français. Pour plus de clarté vaut mieux tout passer en anglais. :)
Pour les erreurs, tu peux mettre des 'raise' à la place des prints ("n'hésite pas à lire dessus!"). Trop bien que tu fasses des checks pour vérifier que le chemin existe, que le suffix est le bon, etc... 👍

2024-01-10 16:50 UTC, llegregam commented on isodesign/io.py
> +        return f"Nom de la molécule : {self.name_mol}, Nombre de carbone(s) associé(s) : {self.num_carbon}"
Au top ça! Juste vaut mieux mettre en anglais pour que le code soit compris par un plus grand nombre de personnes

2024-01-11 09:49 UTC, rkouakou06 commented
Ajout des modifications

2024-01-11 10:11 UTC, llegregam requested changes
Au top! Une  fois que ces changements sont mis en place je pense on pourra merge la branche dévelop dans le main 👍

2024-01-11 10:11 UTC, llegregam commented on isodesign/io.py
> +                        self.mflux = pd.read_csv(data, sep='\t', skiprows=[0])
C'est beaucoup mieux comme ça! Par contre tu peux utiliser des if à la place des elif, c'est un peu plus optimisé et ça laisse la porte ouverte après à la gestion de plusieurs fichiers à la fois (les if successifs n'arrêtent pas l'éxécution du code). Aussi au lieu d'ecrire:
`if data_path.suffix in [".netw"]` 
tu peux tout simplement mettre: 
`if data_path.suffix == ".netw"`.

2024-01-11 10:11 UTC, llegregam commented on isodesign/io.py
> +        try:
Pas besoin de mettre un try... except si tu mets des raise dans la fonction. Je t'expliquerai plus en détails les différents cas d'utilisation du try... except par rapport aux raise!

2024-01-11 10:11 UTC, llegregam commented on isodesign/io.py
> +                raise TypeError(f"An input file is not in right type.")
L'erreur ici devrait plutôt être:
`f"{data} should be of type string and not {type(data)}"`

2024-01-11 10:11 UTC, llegregam commented on isodesign/io.py
> +    print(repr(donnee))
Ici tu peux carrément mettre ça:
`print(donnee)`
Le __repr__ est normalement appelé automatiquement quand tu print l'objet!

2024-01-11 10:30 UTC, rkouakou06 commented
Quand j'enlève le try....except, lorsque je teste une erreur ça me met ça : 
Traceback (most recent call last):
  File "u:\Projet\IsoDesign\isodesign\io.py", line 69, in <module>
    donnee.read_file(1)
  File "u:\Projet\IsoDesign\isodesign\io.py", line 47, in read_file
    raise TypeError(f"{data} should be of type string and not {type(data)}")
TypeError: 1 should be of type string and not <class 'int'>


Je ne sais pas si c'est sensé mettre ça

2024-01-11 10:46 UTC, llegregam requested changes

2024-01-11 10:46 UTC, llegregam commented on isodesign/io.py
> +                    raise TypeError (f"{data_path} is not in the good format\n Only .netw, .tvar, .mflux formats are accepted")
Attention, ici ton else ne va que agir sur le dernier if! Si tu veux checker le format du fichier, tu peux commencer plus haut en notant:
`if data_path.suffix not in [".netw", ".tvar", ".mflux"]:`
` 
raise TypeError (f"{data_path} is not in the good format\n Only .netw, .tvar, .mflux formats are accepted")
`

2024-01-11 10:57 UTC, rkouakou06 commented
Ajout modifs (Désolée je n'ai pas été vigilante pour le else :'-) )

2024-01-11 11:02 UTC, llegregam approved these changes
C'est bueno! Bravo

2024-01-11 11:03 UTC, merged