Dev
MetaboHUB-MetaToul-FluxoMet/IsoDesign pull request #6
Opened 2024-01-18 14:58 UTC by rkouakou06

yo

2024-01-18 15:05 UTC, llegregam approved these changes

2024-01-23 14:33 UTC, rkouakou06 commented
Alors j'ai mis quelques propriétés pour lower_bound et upper_bound pour tester dans un premier temps et que tu puisses voir si c'est bon. 
J'ai compris le concept mais y'a un truc que j'ai pas trop compris au niveau de la syntaxe, j'arriverais pas l'expliquer par écrit j'avoue :-p je te poserai la question de vive voix

2024-01-23 15:29 UTC, llegregam requested changes

2024-01-23 15:29 UTC, llegregam commented on isodesign/process/calculation.py
> +            raise ValueError(f"{value} isn't correct. Use a positive value.")
Je mettrais plutôt "Lower bound for a tracer proportion must be a positive number." car c'est plus explicite

2024-01-23 15:29 UTC, llegregam commented on isodesign/process/calculation.py
> +            raise ValueError(f"{value} isn't correct. Use a positive value.")
Aussi ne vois tu pas d'autres conditions qui devraient renvoyer une erreur? J'en vois au moins une autre moi

2024-01-23 15:29 UTC, llegregam commented on isodesign/process/calculation.py
> +        self._upper_bound = value
Même chose ici. Je mettrais plutôt "proportions are given as a percentage and thus cannot be higher than 100%". Information que l'on devrait mettre dans les docstrings aussi.
Et y'a aussi au moins une autre condition que je vois pour les upper bounds

2024-01-23 15:29 UTC, llegregam commented on isodesign/process/calculation.py
> +            self.mixes.update({"Tracers_mix_combinations" : list(product(*list_combinations))})
Ici il faudra que l'on réfléchisse au stockage des combinaisons finales à utiliser. Peut être créer un attribut dédié plutôt que d'ajouter au dictionnaire.

2024-01-23 15:29 UTC, llegregam commented on isodesign/process/calculation.py
> +            self.mixes.update({"Tracers_mix_combinations" : list(product(*list_combinations))})
Voir limite en faire un dataframe pandas pour garder l'information sur qui a quelle proportion (plus facile a manipuler à terme)

2024-01-23 15:33 UTC, rkouakou06 commented on isodesign/process/calculation.py
> +            self.mixes.update({"Tracers_mix_combinations" : list(product(*list_combinations))})
Le dataframe me semble pas mal, c'est plus simple aussi pour générer les fichiers linp après

2024-01-25 08:38 UTC, rkouakou06 commented
J'ai modifié la méthode tracer_mix_combination pour que cela renvoie une liste des noms et une liste des combinaisons
J'ai commencé à faire la liste des méthodes pour la class process

2024-01-25 08:41 UTC, llegregam approved these changes
Au top!

2024-01-25 08:41 UTC, llegregam commented on isodesign/process/calculation.py
> +        pass
Ici je metterais plutôt import_file ça serait plus clair! Sinon parfait sur tout le reste, je vais te mettre des tâches supplémaentaires dans le issue board

2024-01-25 08:45 UTC, merged