ajout fct read_files et check_files
MetaboHUB-MetaToul-FluxoMet/IsoDesign pull request #7
Opened 2024-01-25 14:05 UTC by rkouakou06

Pour l'importation des fichiers, pour le moment j'ai fais un peu la même approche que celle que tu as fais dans ton fichier io.py dans physiofit, c'est à dire faire une méthode qui lit les fichiers (read_files) et qui fait quelques vérifications sur le chemin qui mène aux fichiers et sur les extensions pour le moment. Ensuite j'ai juste écris le nom de la méthode qui vérifierait le contenu des fichiers (check_files) et qui serait utilisé dans la fonction read_files. 
Je préfère séparer parce que si j'intègre les vérifications du contenu dans la méthode read_files ça peut faire beaucoup de ligne dans une seule méthode je trouve...

2024-01-26 13:48 UTC, llegregam requested changes

2024-01-26 13:48 UTC, llegregam commented on isodesign/process/calculation.py
> +        self.mix.tracer_mix_combination()
Il faut ajouter quelques checks ici quand même je pense

2024-01-26 13:48 UTC, llegregam commented on isodesign/process/calculation.py
> +                        'Value': []})
Mettre directement dans la boucle

2024-01-26 13:48 UTC, llegregam commented on isodesign/process/calculation.py
> +            tracer_isotopomer += [tracer.isotopomer for tracer in tracer_mix]
Peut être une compréhension de liste et directement inséré dans df

2024-01-26 13:48 UTC, llegregam commented on isodesign/process/calculation.py
> +        df["Isotopomer"] = tracer_isotopomer
Peut aller dans dataframe directement

2024-01-26 13:48 UTC, llegregam commented on isodesign/process/calculation.py
> +                    tmp_df.to_csv(fr"test_{pair}.linp", sep="\t")
Mettre la création du df ici.
Enlever les duplicatas de trop.
Créer un dossier pour mettre les linp.
Ajouter les noms générés des linp dans grosse liste.

2024-01-26 14:55 UTC, rkouakou06 commented
J'ai modifié la méthode generate_file mais par contre je n'arrive pas à enlever les duplicatas à la fin, lundi je vais essayer de voir si je trouve un moyen de les enlever ;-)

2024-01-29 08:18 UTC, llegregam approved these changes
C'est ok! Hate de voir la suite :)

2024-01-29 08:18 UTC, merged